name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP environment for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql

      # Wait for MySQL to be healthy
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 --silent; then
              echo "MySQL is ready!";
              break;
            fi
            echo "Waiting for MySQL to be ready...";
            sleep 5;
          done

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Set up .env file and application key
      - name: Set up environment file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Run Laravel tests
      - name: Run tests
        run: php artisan test

      # Log in to Docker Hub (optional, if pushing images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image (optional, if pushing images)
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t your_dockerhub_username/laravel-app:latest .
      #     docker tag your_dockerhub_username/laravel-app:latest your_dockerhub_username/laravel-app:${{ github.sha }}
      #     docker push your_dockerhub_username/laravel-app:latest
      #     docker push your_dockerhub_username/laravel-app:${{ github.sha }}
